GET http://localhost:3002/pokemons

###
GET http://localhost:3001/pokemons/10

###
GET http://localhost:3001/pokemons?name=pokeclau

###
POST http://localhost:3001/pokemons
Content-Type: application/json

{
    "name": "pokeClau2",
    "health": 30,
    "strength": 40,
    "defense": 50,
    "velocity": 60,
    "height": 70,
    "weight":80,
    "types":["rock", "bug", "ghost"]
}

###
GET http://localhost:3001/

###